//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaAsistenciasAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sistemaRFIDEntities1 : DbContext
    {
        public sistemaRFIDEntities1()
            : base("name=sistemaRFIDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int usp_ActualizaAsistencia(Nullable<int> idDetalle, Nullable<int> idEstatus)
        {
            var idDetalleParameter = idDetalle.HasValue ?
                new ObjectParameter("idDetalle", idDetalle) :
                new ObjectParameter("idDetalle", typeof(int));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("idEstatus", idEstatus) :
                new ObjectParameter("idEstatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizaAsistencia", idDetalleParameter, idEstatusParameter);
        }
    
        public virtual ObjectResult<usp_ConsultaRegistrosAsistencias_Result> usp_ConsultaRegistrosAsistencias(string idSalon)
        {
            var idSalonParameter = idSalon != null ?
                new ObjectParameter("idSalon", idSalon) :
                new ObjectParameter("idSalon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultaRegistrosAsistencias_Result>("usp_ConsultaRegistrosAsistencias", idSalonParameter);
        }
    
        public virtual ObjectResult<usp_ConsultaRegistrosAsistencias2_Result> usp_ConsultaRegistrosAsistencias2(string idSalon, Nullable<System.DateTime> horarioSeleccionado)
        {
            var idSalonParameter = idSalon != null ?
                new ObjectParameter("idSalon", idSalon) :
                new ObjectParameter("idSalon", typeof(string));
    
            var horarioSeleccionadoParameter = horarioSeleccionado.HasValue ?
                new ObjectParameter("horarioSeleccionado", horarioSeleccionado) :
                new ObjectParameter("horarioSeleccionado", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultaRegistrosAsistencias2_Result>("usp_ConsultaRegistrosAsistencias2", idSalonParameter, horarioSeleccionadoParameter);
        }
    
        public virtual int usp_GeneraHeaderDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GeneraHeaderDetails");
        }
    
        public virtual ObjectResult<usp_RecuperaHorarios_Result> usp_RecuperaHorarios(string idsalon)
        {
            var idsalonParameter = idsalon != null ?
                new ObjectParameter("idsalon", idsalon) :
                new ObjectParameter("idsalon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RecuperaHorarios_Result>("usp_RecuperaHorarios", idsalonParameter);
        }
    
        public virtual ObjectResult<usp_RecuperaMaestro_Result> usp_RecuperaMaestro(Nullable<int> noEmpleado)
        {
            var noEmpleadoParameter = noEmpleado.HasValue ?
                new ObjectParameter("noEmpleado", noEmpleado) :
                new ObjectParameter("noEmpleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RecuperaMaestro_Result>("usp_RecuperaMaestro", noEmpleadoParameter);
        }
    
        public virtual ObjectResult<usp_RegistraAsistencia_Result> usp_RegistraAsistencia(string mac, string idsalon)
        {
            var macParameter = mac != null ?
                new ObjectParameter("mac", mac) :
                new ObjectParameter("mac", typeof(string));
    
            var idsalonParameter = idsalon != null ?
                new ObjectParameter("idsalon", idsalon) :
                new ObjectParameter("idsalon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RegistraAsistencia_Result>("usp_RegistraAsistencia", macParameter, idsalonParameter);
        }
    }
}
